version: 2.0
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    resource_class: medium
    steps:
      - checkout
      - run:
          name: S P A C E
          command: |
            set -efux

            while :
            do
              echo 'lulz'
              sleep 60
            done

